### ISSUE TITLE
Remove multi release jar

### ISSUE THREAD

**Issue by vietj** [loomania/loomania#2]
IDE (intellij) don't see to correctly use the MRS jar, which makes debugging / tracing impossible.

It seems that the current code could run on lower JVM than 19 and fallback to throwing an exception like currently it does.

Can we remove this to make loomania easier to use ?

**Comment by dmlloyd** [comment]
If you can make it work, then we definitely can do it. The problem is that it has to be compiled with Java 19 with `--enable-preview`, which makes the class file version be a specific version (`61.65535` iirc) that only runs on Java 19 (i.e. not <=18 and not >=20), so I think the classes probably wouldn't load. That's why I did it this way, but maybe there's a way that I didn't think of to make it work.

**Comment by vietj** [comment]
alright, maybe it could be a jar with a java19 classifier for java 19 ?

**Comment by dmlloyd** [comment]
Maybe the solution is to build the source JAR using the java19 sources. I could look into that this morning.

**Comment by dmlloyd** [comment]
I've had an adventure with this, but the end result is this: b176c90

I haven't tried actually deploying this yet but would you be able to build locally to see if this fixes the issue?

**Comment by dmlloyd** [comment]
An update on this; the Java 19 sources are now built with Java 21 with `source`/`target` set to 19. So, they no longer have a preview version at least.

There still might be a way to build the JAR so that the base classes are Java 17 but the Loom-aware classes are Java 19 (compiled on 21). I'm still thinking about it.
